congressional_districts_2020 = {   'CA': 52, 'TX': 38, 'FL': 28, 'NY': 26, 'PA': 17, 
                                   'IL': 17, 'OH': 15, 'GA': 14, 'NC': 14, 'MI': 13, 
                                   'NJ': 12, 'VA': 11, 'WA': 10, 'AZ': 9,  'MA': 9, 
                                   'TN': 9,  'IN': 9,  'MD': 8,  'MO': 8,  'WI': 8, 
                                   'CO': 8,  'MN': 8,  'SC': 7,  'AL': 7,  'LA': 6, 
                                   'KY': 6,  'OR': 6,  'OK': 5,  'CT': 5,  'UT': 4, 
                                   'IA': 4,  'NV': 4,  'AR': 4,  'MS': 4,  'KS': 4, 
                                   'NM': 3,  'NE': 3,  'ID': 2,  'WV': 2,  'HI': 2, 
                                   'NH': 2,  'ME': 2,  'RI': 2,  'MT': 2,  'DE': 1, 
                                   'SD': 1,  'ND': 1,  'AK': 1,  'VT': 1,  'WY': 1 }
